<div id="slider">
	<ul id="gallery">
		
		<li>
			<img src="/images/header/posters/robin-hood.jpg" alt="" />
			<div class="pname">
				<p>ROBIN HOOD 2010</p>
			</div>
			<div class="desc">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dolor tellus, hendrerit<br />vel commod. Lorem ipsum.<br /></p>
				<a href="#1" class="more">SAIBA MAIS</a>
			</div>
		</li>
		
		<li>
			<img src="/images/header/posters/hddescktop.jpg" alt="" />
			<div class="pname">
				<p>ROBIN HOOD 2010</p>
			</div>
			<div class="desc">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dolor tellus, hendrerit<br />vel commod. Lorem ipsum.<br /></p>
				<a href="#2" class="more">SAIBA MAIS</a>
			</div>
		</li>
		
		<li>
			<img src="/images/header/posters/beoriginal.jpg" alt="" />
			<div class="pname">
				<p>ROBIN HOOD 2010</p>
			</div>
			<div class="desc">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dolor tellus, hendrerit<br />vel commod. Lorem ipsum.<br /></p>
				<a href="#3" class="more">SAIBA MAIS</a>
			</div>
		</li>
		
		<li>
			<img src="/images/header/posters/hddescktop.jpg" alt="" />
			<div class="pname">
				<p>ROBIN HOOD 2010</p>
			</div>
			<div class="desc">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dolor tellus, hendrerit<br />vel commod. Lorem ipsum.<br /></p>
				<a href="#" class="more">SAIBA MAIS</a>
			</div>
		</li>
		
		<li>
			<img src="/images/header/posters/robin-hood.jpg" alt="" />
			<div class="pname">
				<p>ROBIN HOOD 2010</p>
			</div>
			<div class="desc">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dolor tellus, hendrerit<br />vel commod. Lorem ipsum.<br /></p>
				<a href="#" class="more">SAIBA MAIS</a>
			</div>
		</li>
		
		<li>
			<img src="/images/header/posters/beoriginal.jpg" alt="" />
			<div class="pname">
				<p>ROBIN HOOD 2010</p>
			</div>
			<div class="desc">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dolor tellus, hendrerit<br />vel commod. Lorem ipsum.<br /></p>
				<a href="#" class="more">SAIBA MAIS</a>
			</div>
		</li>
		
	</ul>
</div>

<div class="flash">
	<?php $this->partial('elements/advertising/mRec.phtml') ?>
</div>
