<div class="min-width">
		
			<div class="box1">
				<div class="tail-bottom">
				<div class="corner-right-top">
				<div class="corner-left-top">
				<div class="corner-right-bottom">
				<div class="corner-left-bottom">
				<div class="top-bg">
				<div class="bottom-bg">
					<div class="indent">
						<img alt="" src="images/home-title1.gif" class="title" /><br />
						Lorem ipsum dolor sit amet, consectetur adipisicing elit do eiusmod tempor incidiunt.<br />
						<div class="link">
							<a href="#">Read more</a>
						</div>
					</div>
				</div>
				</div>
				</div>
				</div>
				</div>
				</div>
				</div>
			</div>
			
			<div class="box2">
				<div class="tail-bottom">
				<div class="corner-right-top">
				<div class="corner-left-top">
				<div class="corner-right-bottom">
				<div class="corner-left-bottom">
				<div class="top-bg">
				<div class="bottom-bg">
					<div class="indent">
						<img alt="" src="images/home-title2.gif" class="title" /><br />
						Lorem ipsum dolor sit amet, consectetur adipisicing elit do eiusmod tempor incidiunt.<br />
						<div class="link">
							<a href="#">Read more</a>
						</div>
					</div>
				</div>
				</div>
				</div>
				</div>
				</div>
				</div>
				</div>
			</div>
		</div>	