<head>
	<title><?php echo implode(' | ', $this->breadcumbsTitles)?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="<?php echo $this->metaDescription ?>" />
	<meta name="keywords" content=""<?php echo $this->metaKeywords ?> />
	<link href="/css/style.css" type="text/css" rel="stylesheet" />
	<script type="text/javascript" src="/js/jquery-1.4.3.min.js"></script>
	<script type="text/javascript" src="/js/scripts.js"></script>
	<script type="text/javascript">
		/* JQUERY RATING PLUGIN LOAD START */
		$('input.star').rating();
		/* JQUERY RATING PLUGIN LOAD END */
	</script>
</head>