<!--action index index-->
<div class="colleft">
	
	
	<!--?php $this->partial('elements/colleft/menu.phtml') ?-->
	
	
</div>


<!-- sidebar start -->
<div class="sidebar">
	
	<!--?php $this->partial('elements/advertising/mSmall.phtml') ?-->
	
	
	<!--?php $this->partial('elements/sliderbars/currentMonth.phtml') ?-->
	
	
	<!--?php $this->partial('elements/sliderbars/poll.phtml') ?-->
	
	
	<!--?php $this->partial('elements/advertising/mSmall.phtml') ?-->
	
	
	<!--?php $this->partial('elements/sliderbars/traillers.phtml') ?-->
	
	
	<!--?php $this->partial('elements/advertising/mSmall.phtml') ?-->
	
</div>
<!-- sidebar end -->