		<div class="notfound">

            <div class="title">
                <h2><span>Página não encontrada</span></h2>
                <div class="reset"></div>
            </div>

            <h3 class="tight">Lamentamos mas não foi possível encontrar a página que pediu.</h3>

            <div class="image left">

            </div>

            <div class="text">

                <p>O endereço que procura pode ter sido alterado, estar temporariamente indisponível ou a página pode ter sido removida.</p>

                <p>O endereço solicitado foi:
                    <strong class="address"><?php echo htmlentities($_REQUEST['url']) ?></strong>
                </p>

                <h3 class="tight">Sugerimos:</h3>

                <ul class="text">
                   <li>Verifique se o endereço que introduziu está correcto;</li>
                   <li>Regresse <a href="/">à página inicial</a></li>
                   <li>Efectue uma pesquisa sobre o tema da página pretendida.</li>
                </ul>

            </div>

        </div>